### ISSUE TITLE
Question about the theme

### ISSUE THREAD

**Issue by Serendipia2** [webketje/notepad-plus-plus-duotone-dark-theme#1]
I can see that some languages uses currently all Duo-colours (CSS, HTML, C) but others (R) doesn't. Is any specific reason for this?

**Comment by webketje** [comment]
Hi @RMRubert , the reason is that it takes quite some time to style each language and so I focused on the ones I use most first. The ones that are not duotone are basically the Zenburn theme with a different background. Would you like R to be included in the list of supported languages?

**Comment by Serendipia2** [comment]
Using the Python one as a guide I have the feeling this configuration shouldn't look too bad:

`		<LexerType name="r" desc="R" ext="">
            <WordsStyle name="DEFAULT" styleID="0" fgColor="{{ UNO2 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMMENT" styleID="1" fgColor="{{ UNO4 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="2" fontSize="" />
            <WordsStyle name="INSTRUCTION WORD" styleID="2" fgColor="{{ DUO3 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" keywordClass="instre1" />
            <WordsStyle name="BASE WORD" styleID="3" fgColor="{{ DUO2 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" keywordClass="instre2" />
            <WordsStyle name="KEYWORD" styleID="4" fgColor="{{ UNO1 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" keywordClass="type1" />
            <WordsStyle name="NUMBER" styleID="5" fgColor="{{ DUO1 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="6" fgColor="{{ DUO1 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING2" styleID="7" fgColor="{{ DUO1 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="8" fgColor="{{ DUO2 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="INFIX" styleID="10" fgColor="{{ DUO2 }}" bgColor="{{ BACKGROUND }}" fontName="" fontStyle="0" fontSize="" />
        </LexerType>`

**Comment by webketje** [comment]
@RMRubert R will be included in the next release, see 0ed1484173339. I took your example as a base, thanks for your contribution!
